/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestingProject;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author ahmed
 */
public class SelectScreenFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectScreenFrame
     */
    public SelectScreenFrame() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null); //To center the window hen it launches
        setResizable(false);
        fromTextField.setVisible(false);
        toTextField.setVisible(false);
        fromLabel.setVisible(false);
        toLabel.setVisible(false);
        iAmReadyButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        allQuestionsRadioButton = new javax.swing.JRadioButton();
        chooseRangeRadioButton = new javax.swing.JRadioButton();
        fromLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toLabel = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        iAmReadyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to the Testing Center ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 16, 741, -1));

        jLabel2.setText("Select The Questions you want to be tested on (1 - 5):");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 78, -1, -1));

        optionsButtonGroup.add(allQuestionsRadioButton);
        allQuestionsRadioButton.setText("All Questions (1 - 5)");
        allQuestionsRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                allQuestionsRadioButtonStateChanged(evt);
            }
        });
        allQuestionsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allQuestionsRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(allQuestionsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 110, -1, -1));

        optionsButtonGroup.add(chooseRangeRadioButton);
        chooseRangeRadioButton.setText("Choose a Range");
        chooseRangeRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chooseRangeRadioButtonStateChanged(evt);
            }
        });
        chooseRangeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRangeRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chooseRangeRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 157, -1, -1));

        fromLabel.setText("From:");
        getContentPane().add(fromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 207, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 204, -1, -1));
        getContentPane().add(fromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 204, 49, -1));

        toLabel.setText("To :");
        getContentPane().add(toLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 207, -1, -1));
        getContentPane().add(toTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 204, 55, -1));

        iAmReadyButton.setText("I Am Ready!");
        iAmReadyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iAmReadyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(iAmReadyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 129, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 1527, 118, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TestingProject/Wallpaper.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1020, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void allQuestionsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allQuestionsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allQuestionsRadioButtonActionPerformed

    private void chooseRangeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRangeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseRangeRadioButtonActionPerformed

    private void iAmReadyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iAmReadyButtonActionPerformed
        if(evt.getSource() == iAmReadyButton) {
            if(allQuestionsRadioButton.isSelected() == true)
                if(isInputCorrect(fromTextField, toTextField) == false && allQuestionsRadioButton.isSelected() == false) {
                    JOptionPane.showMessageDialog(null, "You must enter the number for the questions you want to be tested on (1 - 5)");
                } else {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new OnlineTestingFrame().setVisible(true);
                        }
                    });
                    this.setVisible(false);
                }
        } else {
            if (isInputCorrect(fromTextField, toTextField) == false && allQuestionsRadioButton.isSelected() == false) { 
                JOptionPane.showMessageDialog(null, "You must enter the number for the questions you want to be tested on (1 - 5)");
            } else {
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new OnlineTestingFrame(fromTextField.getText() , toTextField.getText()).setVisible(true);
                        }
                    });
                    this.setVisible(false);
            }
        }
    }//GEN-LAST:event_iAmReadyButtonActionPerformed

    private void allQuestionsRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_allQuestionsRadioButtonStateChanged
        if (allQuestionsRadioButton.isSelected() == true) {
            iAmReadyButton.setEnabled(true);
        }else{
            // it does not do anything
        }
    }//GEN-LAST:event_allQuestionsRadioButtonStateChanged

    private void chooseRangeRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chooseRangeRadioButtonStateChanged
        if(chooseRangeRadioButton.isSelected() == true) {
            fromTextField.setVisible(true);
            toTextField.setVisible(true);
            fromLabel.setVisible(true);
            toLabel.setVisible(true);
            iAmReadyButton.setEnabled(true);
        } else {
            fromTextField.setVisible(false);
            toTextField.setVisible(false);
            fromLabel.setVisible(false);
            toLabel.setVisible(false);
        }
    }//GEN-LAST:event_chooseRangeRadioButtonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectScreenFrame().setVisible(true);
            }
        });
    }
    public boolean isInputCorrect(JTextField from, JTextField to) {
        int IntFrom;
        int IntTo;
        
        try{
            Integer.parseInt(from.getText());
            IntFrom = Integer.parseInt(from.getText());
        } catch (Exception e) {
            return false;
        }
        try {
            Integer.parseInt(to.getText());
            IntTo = Integer.parseInt(to.getText());
            
        } catch (Exception e) {
            return false;
        }
        if(from.getText().equals("") || to.getText().equals("")) {
            return false;
        } else if (IntFrom < 1 || IntFrom > 5 || IntTo > 5) {
            return false;
        } else  {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allQuestionsRadioButton;
    private javax.swing.JRadioButton chooseRangeRadioButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JButton iAmReadyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.ButtonGroup optionsButtonGroup;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables
}
